media:
  input: public
  output: /

content:
  - name: homepage
    label: "Homepage"
    type: file
    path: "src/content/homepage.json"
    format: json
    fields:
      - name: headlinePre
        label: "Headline (Text Before Highlight)"
        type: string
      - name: headlineHighlight
        label: "Headline (Highlighted Text)"
        type: string
      - name: headlinePost
        label: "Headline (Text After Highlight)"
        type: string
      - name: subheadline
        label: "Subheadline"
        type: string
      - name: buttonText
        label: "Button Text"
        type: string
      - name: buttonUrl
        label: "Button URL"
        type: string